### ISSUE TITLE
BreadController should extend App\Http\Controllers\Controller

### ISSUE THREAD

**Issue by mosbror** [jesperbjerke/laravel-bread#1]
BreadController should extend "App\Http\Controllers\Controller" instead of "Illuminate\Routing\Controller".
To not lose the _AuthorizesRequests_, _DispatchesJobs_ and _ValidatesRequests_ traits.

Please let me know what you think.

**Comment by jesperbjerke** [comment]
That controller class is something that is included in the base installation of Laravel and lives in your project code, not Laravel itself. If BreadController would extend on that, it would enforce all projects to have that setup, which might not be case. There's also a point in BreadController only extending the most base version of what it needs and not enforce more things to be included than it needs to operate.

If you'd like to always have those traits included in all your controllers, you can create your own "base" controller, which extends BreadController and then include those traits in there :)
